# [重要参数勿动]小程序验证相关信息
appid=wxaaff018e79374ad2
secret=70011ec23f88e5e1f0ab6441c97c6001
grant_type=authorization_code
checkUrl=https://api.weixin.qq.com/sns/jscode2session

# 权限验证token参数,除开过期时间,其他勿动
token.header=X_Auth_Token
token.secret=secret
token.expiration=604800

# 当前项目版本
version=1.1.00

# jdbc
driver=com.mysql.jdbc.Driver
url=jdbc:mysql://47.107.52.39:3306/time_doser
username=root
password=tcyeeeTimeDoser;

# redis
redis_password=
redis_host=134.175.157.42
redis_port=6379