version: "3"
services:

  # eureka 如果是阿里节点
  ali-eureka:
    image: tcyeee/microservice-discovery-eureka:0.0.4
    hostname: server-ali
    ports:
      - "2100:2100"
    environment:
      - spring.profiles.active=server-ali

  # eureka 如果是腾讯节点
  tx-eureka:
    image: tcyeee/microservice-discovery-eureka:0.0.4
    hostname: server-tx
    ports:
      - "2100:2100"
    environment:
      - spring.profiles.active=server-tx

  # 网关
  microservice-gateway-zuul:
    image: tcyeee/microservice-gateway-zuul:0.0.5
    ports:
      - "2110:2110"
    environment:
      - spring.profiles.active=server-online