eureka:
  client:
    service-url:
      # 如果是docker启动的话,需要修改localhost为local-eureka,因为在docker的每个实例中localhost解析出来都是不一样的
       defaultZone: http://cy:123@local-eureka:2100/eureka/
#      defaultZone: http://cy:123@localhost:2100/eureka/
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/time_doser_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: cy19X_my!@#
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: error
