server:
  port: 2110
zuul:
  routes:
    module-user: /user/**
    module-main: /main/**
spring:
  application:
    name: microservice-gateway-zuul
  redis:
    database: 0
    host: 134.175.157.42
    port: 6379
    password: cyRdis;TimeDoer123
    timeout: 6000ms
    jedis:
      pool:
        max-active: -1
        max-idle: 64
        min-idle: 1
        max-wait: -1ms