server:
  port: 2110
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:2100/eureka/,http://peer2:2100/eureka/
  instance:
    prefer-ip-address: true