server:
  port: 1901  # 服务器访问端口
  servlet:
    context-path: /timeDoser # 现在有多个项目,用于区分, 则加上名称空间

spring:
  datasource:
    url: ${url}?useUnicode=true&characterEncoding=UTF-8
    username: ${username}
    password: ${password}
    driver-class-name: ${driver}
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: MYSQL
    show-sql: true                 # 是否显示后台处理的SQL语句
#    hibernate.ddl-auto: update     # 自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表(只有创建新表的时候启用这个,否则每次启动都会检查外键)

# 调整日志级别
logging:
  level:
    root: warn
---
# Mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: partial
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
---
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
---

