# [重要参数勿动]小程序验证相关信息
appid=wxab9666589819e2ee
secret=b9f23ea0284c09a408b407f9253e826c
grant_type=authorization_code
checkUrl=https://api.weixin.qq.com/sns/jscode2session

# 权限验证token参数,除开过期时间,其他勿动
token.header=X_Auth_Token
token.secret=secret
token.expiration=604800