eureka:
  client:
    service-url:
      defaultZone: http://cy:123@localhost:2100/eureka/
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/time_doser?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: cy19X_my!@#
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: error