server:
  port: 1902
  servlet:
    context-path: /main
spring:
  application:
    name: module-main
  datasource:
    url: jdbc:mysql://47.107.52.39:3306/time_doser_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: tcyeeeTimeDoser;
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
# Mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: partial
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql