server:
  port: 1902
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: module-main
eureka:
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml