server:
  port: 1901  # 服务器访问端口
#  servlet:
#    context-path: /timeDoser/user # 现在有多个项目,用于区分, 则加上名称空间
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://47.107.52.39:3306/time_doser_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: tcyeeeTimeDoser;
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://cy:123@localhost:2100/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: info


# Mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: partial
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql