spring:
  application:
    name: microservice-discovery-eureka
  security:
    user:
      name: cy                  # 配置登录的账号是cy
      password: 123             # 配置登录的密码是123
server:
  port: 2100
---
spring:
  profiles: server-ali
eureka:
  instance:
    hostname: server-ali    # 显示在eureka上的名称
  client:
    serviceUrl:
      defaultZone: http://cy:123@134.175.157.42:2100/eureka/
---
spring:
  profiles: server-tx
eureka:
  instance:
    hostname: server-tx
  client:
    serviceUrl:
      defaultZone: http://cy:123@47.107.52.39:2100/eureka/
---
spring:
  profiles: server-local
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cy:123@localhost:2100/eureka/