spring:
  application:
    name: microservice-discovery-eureka
---
spring:
  profiles: server-ali                                             # 指定profile=peer1
server:
  port: 2100
eureka:
  instance:
    hostname: server-ali                                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://cy:123@134.175.157.42:2100/eureka/      # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: server-tx
server:
  port: 2100
eureka:
  instance:
    hostname: server-tx
  client:
    serviceUrl:
      defaultZone: http://cy:123@47.107.52.39:2100/eureka/