package demo.tcyeee.entity.enums.base;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 项目所用到的logo
 *
 * @author huxiong
 * @date 2020/1/17 16:55
 */
@Getter
@AllArgsConstructor
public enum IconEnum {

    appreciate(0, "appreciate"),
    check(1, "check"),
    emoji(2, "emoji"),
    favor(3, "favor"),
    loading(4, "loading"),
    location(5, "location"),
    roundcheck(6, "roundcheck"),
    roundright(7, "roundright"),
    search(8, "search"),
    taxi(9, "taxi"),
    time(10, "time"),
    warn(11, "warn"),
    camera(12, "camera"),
    like(13, "like"),
    order(14, "order"),
    deliver(15, "deliver"),
    evaluate(16, "evaluate"),
    send(17, "send"),
    shop(18, "shop"),
    ticket(19, "ticket"),
    cascades(20, "cascades"),
    discover(21, "discover"),
    form(22, "form"),
    pic(23, "pic"),
    filter(24, "filter"),
    footprint(25, "footprint"),
    pullup(26, "pullup"),
    right(27, "right"),
    cart(28, "cart"),
    remind(29, "remind"),
    home(30, "home"),
    addressbook(31, "addressbook"),
    link(32, "link"),
    lock(33, "lock"),
    unlock(34, "unlock"),
    goods(35, "goods"),
    selection(36, "selection"),
    explore(37, "explore"),
    present(38, "present"),
    square(39, "square"),
    round(40, "round"),
    game(41, "game"),
    similar(42, "similar"),
    vipcard(43, "vipcard"),
    camerarotate(44, "camerarotate"),
    light(45, "light"),
    flashlightopen(46, "flashlightopen"),
    copy(47, "copy"),
    notice(48, "notice"),
    upstage(49, "upstage"),
    baby(50, "baby"),
    brand(51, "brand"),
    clothes(52, "clothes"),
    creative(53, "creative"),
    female(54, "female"),
    male(55, "male"),
    rank(56, "rank"),
    bad(57, "bad"),
    cameraadd(58, "cameraadd"),
    focus(59, "focus"),
    album(60, "album"),
    people(61, "people"),
    file(62, "file"),
    attention(63, "attention"),
    community(64, "community"),
    read(65, "read"),
    calendar(66, "calendar"),
    magic(67, "magic"),
    tag(68, "tag"),
    all(69, "all"),
    hot(70, "hot"),
    post(71, "post"),
    write(72, "write"),
    safe(73, "safe"),
    crown(74, "crown"),
    text(75, "text"),
    musicfill(76, "musicfill"),
    record(77, "record"),
    cardboard(78, "cardboard"),
    mail(79, "mail"),
    goodsnew(80, "goodsnew"),
    medal(81, "medal"),
    newshot(82, "newshot"),
    news(83, "news"),
    skin(84, "skin"),
    usefull(85, "usefull");

    private int index;
    private String name;
}
